# Generated by Django 4.1 on 2023-11-21 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendor", "0002_alter_vendor_average_response_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "po_number",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("order_date", models.DateTimeField(auto_now=True)),
                ("delivery_date", models.DateTimeField(auto_now=True)),
                ("items", models.JSONField()),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quality_rating", models.FloatField()),
                ("issue_date", models.DateTimeField()),
                ("acknowledgment_date", models.DateTimeField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vendor.vendor",
                    ),
                ),
            ],
        ),
    ]
