# Generated by Django 4.2.7 on 2023-12-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "po_number",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("order_date", models.DateTimeField(null=True)),
                ("delivery_date", models.DateTimeField(null=True)),
                ("actual_delivery_date", models.DateTimeField(default=None, null=True)),
                ("items", models.JSONField()),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quality_rating", models.FloatField(null=True)),
                ("issue_date", models.DateTimeField(null=True)),
                ("acknowledgement_date", models.DateTimeField(null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vendor.vendor",
                    ),
                ),
            ],
        ),
    ]
