# Generated by Django 4.2.7 on 2023-11-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_purchaseorder_acknowledgment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="actual_delivery_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
