# Generated by Django 4.2.7 on 2023-11-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_purchaseorder_actual_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(null=True),
        ),
    ]
