# Generated by Django 4.2.7 on 2023-11-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_purchaseorder_acknowledgment_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="acknowledgment_date",
            new_name="acknowledgement_date",
        ),
    ]
