# Generated by Django 4.2.7 on 2023-12-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_rename_acknowledgment_date_purchaseorder_acknowledgement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="quality_rating",
            field=models.FloatField(null=True),
        ),
    ]
